### PR TITLE
adds data manipulation sql functions

### LINKED ISSUE #13: Data persistence
All data should be ultimately stored in the linked mongodb server.

Firstly complete this task https://github.com/Toumash/hearty/issues/10

## Entites to store
 - subscriptions
 - links
 - userIds

## Proposal
NoSQL data sctucture
```
{
  "users": {
    "user-id": {
      "subscription": {}
    }
  },
  "invitations": {
    "invite-id": "user-id"
  }
}
```
Todo:
 - [ ] History of interactions

## Tasks:
 - [x] create db model
 - [ ] use database instead of in-memory cache from [here](https://github.com/Toumash/hearty/issues/10)

### PR DESCRIPTION
**Pull request by Toumash**
closes #13 

- [x] sql model
- [x] sql migration from in-memory
- [x] sql history of interactions

# Tested
- [x] GET /api/user/invite-link
- [x] POST /api/accept-invite/:invitationCode'
- [x] GET /api/partner
- [x] POST /api/user
- [x] GET /
- [x] POST /api/send-love
- [x] GET /receive-love
- [x] GET /user/accept-invite/:invitationCode
- [x] GET /api/db

### CODE REVIEW

**Comment by Toumash** [comment]
We've got it working! Needs more testing (the rest of the endpoints) @AlicjaDobrzeniecka 
image

**Comment by Toumash** [comment]
Events także done 
image

**Comment by Toumash** [comment]
@AlicjaDobrzeniecka czekam na review i mozna wdrażać. Trzeba to przetestować dobrze - pasy do mongodb masz ;)

**Comment by Toumash** [comment]
jbc przetestowane. Pozostaja nam tylko bledy frontendu

**Review by efemeryds — APPROVED** [review]

**Pull request merged**
